<?php

use App\Http\Controllers\Api\AuthController;
use App\Http\Controllers\Api\CommunicationLogController;
use App\Http\Controllers\Api\AppNotificationController;
use App\Http\Controllers\Api\RewardController;
use App\Http\Controllers\Api\CustomerController;
use App\Http\Controllers\Api\CustomerCategoryRuleController;
use App\Http\Controllers\Api\CustomerImportantDateController;
use App\Http\Controllers\Api\CustomOrderController;
use App\Http\Controllers\Api\DashboardController;
use App\Http\Controllers\Api\ExhibitionController;
use App\Http\Controllers\Api\FestivalCampaignController;
use App\Http\Controllers\Api\FollowupController;
use App\Http\Controllers\Api\GiftCardController;
use App\Http\Controllers\Api\LeadController;
use App\Http\Controllers\Api\LoyaltyController;
use App\Http\Controllers\Api\MarketingCampaignController;
use App\Http\Controllers\Api\MessageTemplateController;
use App\Http\Controllers\Api\OfferController;
use App\Http\Controllers\Api\PrivilegeCardController;
use App\Http\Controllers\Api\ReportController;
use App\Http\Controllers\Api\RetentionController;
use App\Http\Controllers\Api\SaleController;
use App\Http\Controllers\Api\SettingController;
use App\Http\Controllers\Api\SmartTaskController;
use App\Http\Controllers\Api\StaffController;
use App\Http\Controllers\Api\TaskController;
use App\Http\Controllers\Api\TaskRuleController;
use Illuminate\Support\Facades\Route;

Route::post('auth/login', [AuthController::class, 'login'])->name('login');
Route::post('events/{token}/capture', [ExhibitionController::class, 'capture'])->name('events.capture');

Route::middleware(['auth:sanctum', 'module.permission'])->group(function () {
    Route::get('auth/me', [AuthController::class, 'me']);
    Route::post('auth/logout', [AuthController::class, 'logout']);
    Route::get('dashboard', DashboardController::class);
    Route::post('leads/import', [LeadController::class, 'import']);
    Route::get('leads/export', [LeadController::class, 'export']);
    Route::post('leads/{lead}/convert', [LeadController::class, 'convert']);
    Route::post('leads/{lead}/notes', [LeadController::class, 'addNote']);
    Route::get('leads/{lead}/journey', [LeadController::class, 'journey']);
    Route::apiResource('leads', LeadController::class);
    Route::apiResource('followups', FollowupController::class);
    Route::post('customers/import-excel', [CustomerController::class, 'import']);
    Route::get('customers/excel-template', [CustomerController::class, 'excelTemplate']);
    Route::post('customers/recategorize', [CustomerController::class, 'recategorize']);
    Route::apiResource('customers', CustomerController::class);
    Route::apiResource('customer-category-rules', CustomerCategoryRuleController::class)->except('show');
    Route::apiResource('sales', SaleController::class)->except('update');
    Route::post('custom-orders/{customOrder}/status', [CustomOrderController::class, 'status']);
    Route::apiResource('custom-orders', CustomOrderController::class);
    Route::get('exhibitions/{exhibition}/roi', [ExhibitionController::class, 'roi']);
    Route::apiResource('exhibitions', ExhibitionController::class);
    Route::apiResource('offers', OfferController::class);
    Route::get('marketing/dashboard', [MarketingCampaignController::class, 'dashboard']);
    Route::post('marketing/preview', [MarketingCampaignController::class, 'preview']);
    Route::post('marketing-campaigns/{marketingCampaign}/launch', [MarketingCampaignController::class, 'launch']);
    Route::patch('campaign-recipients/{campaignRecipient}/engagement', [MarketingCampaignController::class, 'engagement']);
    Route::apiResource('marketing-campaigns', MarketingCampaignController::class)->parameters(['marketing-campaigns' => 'marketingCampaign']);
    Route::get('loyalty', [LoyaltyController::class, 'index']);
    Route::get('loyalty/{customer}', [LoyaltyController::class, 'wallet']);
    Route::post('loyalty/{customer}/adjust', [LoyaltyController::class, 'adjust']);
    Route::post('gift-cards/{giftCard}/redeem', [GiftCardController::class, 'redeem']);
    Route::apiResource('gift-cards', GiftCardController::class);
    Route::apiResource('privilege-cards', PrivilegeCardController::class);
    Route::apiResource('tasks', TaskController::class);
    Route::get('retention/messages/today', [RetentionController::class, 'today']);
    Route::get('retention/messages/upcoming', [RetentionController::class, 'upcoming']);
    Route::get('retention/messages/winback', [RetentionController::class, 'winback']);
    Route::get('retention/messages/vip', [RetentionController::class, 'vip']);
    Route::get('retention/messages', [RetentionController::class, 'index']);
    Route::post('retention/messages/{message}/mark-copied', [RetentionController::class, 'action'])->defaults('action', 'copied');
    Route::post('retention/messages/{message}/mark-whatsapp-opened', [RetentionController::class, 'action'])->defaults('action', 'whatsapp_opened');
    Route::post('retention/messages/{message}/mark-contacted', [RetentionController::class, 'action'])->defaults('action', 'contacted');
    Route::post('retention/messages/{message}/ignore', [RetentionController::class, 'action'])->defaults('action', 'ignored');
    Route::post('retention/messages/{message}/create-followup', [RetentionController::class, 'createFollowup']);
    Route::post('retention/scan', [RetentionController::class, 'scan']);
    Route::get('customers/{customer}/retention-profile', [RetentionController::class, 'profile']);
    Route::get('customers/{customer}/important-dates', [CustomerImportantDateController::class, 'index']);
    Route::post('customers/{customer}/important-dates', [CustomerImportantDateController::class, 'store']);
    Route::put('customer-important-dates/{customerImportantDate}', [CustomerImportantDateController::class, 'update']);
    Route::delete('customer-important-dates/{customerImportantDate}', [CustomerImportantDateController::class, 'destroy']);
    Route::apiResource('message-templates', MessageTemplateController::class)->except('show')->parameters(['message-templates' => 'messageTemplate']);
    Route::apiResource('festival-campaigns', FestivalCampaignController::class)->except('show')->parameters(['festival-campaigns' => 'festivalCampaign']);
    Route::get('smart-work/dashboard', [SmartTaskController::class, 'dashboard']);
    Route::get('smart-tasks/today', [SmartTaskController::class, 'today']);
    Route::get('smart-tasks/overdue', [SmartTaskController::class, 'overdue']);
    Route::get('smart-tasks/upcoming', [SmartTaskController::class, 'upcoming']);
    Route::get('smart-tasks/high-priority', [SmartTaskController::class, 'highPriority']);
    Route::get('smart-tasks/my-tasks', [SmartTaskController::class, 'myTasks']);
    Route::post('smart-tasks/generate', [SmartTaskController::class, 'generate']);
    Route::get('smart-tasks', [SmartTaskController::class, 'index']);
    Route::get('smart-tasks/{smartTask}', [SmartTaskController::class, 'show']);
    Route::post('smart-tasks/{smartTask}/start', [SmartTaskController::class, 'start']);
    Route::post('smart-tasks/{smartTask}/complete', [SmartTaskController::class, 'complete']);
    Route::post('smart-tasks/{smartTask}/skip', [SmartTaskController::class, 'skip']);
    Route::post('smart-tasks/{smartTask}/reschedule', [SmartTaskController::class, 'reschedule']);
    Route::post('smart-tasks/{smartTask}/create-followup', [SmartTaskController::class, 'createFollowup']);
    Route::post('smart-tasks/{smartTask}/send-whatsapp-log', [SmartTaskController::class, 'whatsapp']);
    Route::post('task-rules/{taskRule}/toggle', [TaskRuleController::class, 'toggle']);
    Route::apiResource('task-rules', TaskRuleController::class)->except('show')->parameters(['task-rules' => 'taskRule']);
    Route::apiResource('communications', CommunicationLogController::class);
    Route::get('reports/{type}', [ReportController::class, 'index']);
    Route::get('settings', [SettingController::class, 'index']);
    Route::put('settings', [SettingController::class, 'update']);
    Route::post('settings/branches', [SettingController::class, 'branch']);
    Route::put('settings/branches/{branch}', [SettingController::class, 'updateBranch']);
    Route::delete('settings/branches/{branch}', [SettingController::class, 'deleteBranch']);
    Route::post('settings/roles', [SettingController::class, 'createRole']);
    Route::put('settings/roles/{role}', [SettingController::class, 'updateRole']);
    Route::put('settings/roles/{role}/permissions', [SettingController::class, 'rolePermissions']);
    Route::get('staff/{staff}/performance', [StaffController::class, 'performance']);
    Route::apiResource('staff', StaffController::class);
    Route::get('notifications', [AppNotificationController::class, 'index']);
    Route::post('notifications/read-all', [AppNotificationController::class, 'readAll']);
    Route::post('notifications/{notification}/read', [AppNotificationController::class, 'read']);
    Route::get('rewards', [RewardController::class, 'index']);
    Route::post('rewards/{reward}/redeem', [RewardController::class, 'redeem']);
    Route::get('reward-redemptions', [RewardController::class, 'redemptions']);
    Route::patch('reward-redemptions/{redemption}/decide', [RewardController::class, 'decide']);
});
