export const modules={
 leads:{title:'Leads',singular:'Lead',endpoint:'leads',columns:[['name','Lead'],['mobile','Mobile'],['assignee.name','Salesperson'],['source','Source'],['priority','Priority'],['status','Status']],filters:{status:['New','Contacted','Interested','Follow-up','Converted','Lost'],priority:['Hot','Warm','Cold'],source:['Walk-in','Instagram','Facebook','WhatsApp','Website','Referral','Exhibition','Event','Phone Call']},fields:[['name','Name','text',true],['mobile','Mobile','tel',true],['email','Email','email'],['assigned_to','Assign salesperson','select',true,[]],['source','Lead source','select',false,['Walk-in','Instagram','Facebook','WhatsApp','Website','Referral','Exhibition','Event','Phone Call']],['status','Status','select',false,['New','Contacted','Interested','Follow-up','Converted','Lost']],['priority','Priority','select',false,['Hot','Warm','Cold']],['occasion','Occasion'],['budget_min','Minimum budget','number'],['budget_max','Maximum budget','number'],['notes','Notes','textarea']]},
 followups:{title:'Follow-ups',singular:'Follow-up',endpoint:'followups',columns:[['lead.name','Lead / customer'],['type','Channel'],['scheduled_at','Scheduled'],['assignee.name','Owner'],['status','Status']],filters:{status:['Pending','Completed','Cancelled','Overdue'],type:['Call','WhatsApp','Visit','Meeting','Email']},fields:[['lead_id','Lead ID','number'],['customer_id','Customer ID','number'],['type','Type','select',true,['Call','WhatsApp','Visit','Meeting','Email']],['scheduled_at','Date & time','datetime-local',true],['status','Status','select',false,['Pending','Completed','Cancelled','Overdue']],['notes','Notes','textarea'],['outcome','Outcome','textarea']]},
 customers:{title:'Customers',singular:'Customer',endpoint:'customers',columns:[['customer_code','Code'],['name','Customer'],['mobile','Mobile'],['category','Auto category'],['loyalty_balance','Points']],filters:{category:['Normal','Premium','VIP','HNI']},fields:[['name','Name','text',true],['mobile','Mobile','tel',true],['email','Email','email'],['birthday','Birthday','date'],['anniversary','Anniversary','date'],['city','City'],['address','Address','textarea'],['notes','Notes','textarea']]},
 'custom-orders':{title:'Custom Orders',singular:'Custom order',endpoint:'custom-orders',columns:[['order_number','Order'],['customer.name','Customer'],['jewellery_type','Jewellery'],['due_date','Due date'],['status','Status']],filters:{status:['Processing','Cancelled','Order Ready']},fields:[['customer_id','Customer ID','number',true],['jewellery_type','Jewellery type','text',true],['metal_type','Metal type','select',true,['Gold','Rose Gold','Platinum','Silver']],['purity','Purity','select',false,['18K','22K','24K','925']],['approx_weight','Approx. weight (g)','number'],['estimated_amount','Estimated amount','number',true],['advance_payment','Advance payment','number'],['due_date','Due date','date',true],['status','Status','select',true,['Processing','Cancelled','Order Ready']],['vendor_name','Karigar / vendor'],['approval_status','Customer approval','select',false,['Pending','Approved','Rejected']],['internal_notes','Internal notes','textarea']]},
 exhibitions:{title:'Exhibitions & Events',singular:'Event',endpoint:'exhibitions',columns:[['name','Event'],['location','Location'],['start_date','Starts'],['stall_number','Stall'],['status','Status']],filters:{status:['upcoming','active','completed','cancelled']},fields:[['name','Event name','text',true],['location','Location','text',true],['start_date','Start date','date',true],['end_date','End date','date',true],['stall_number','Stall number'],['expense','Event expense','number'],['status','Status','select',false,['upcoming','active','completed','cancelled']],['notes','Notes','textarea']]},
 offers:{title:'Offers & Campaigns',singular:'Offer',endpoint:'offers',columns:[['title','Offer'],['type','Type'],['start_date','Starts'],['end_date','Ends'],['status','Status']],filters:{status:['Active','Inactive','Expired'],type:['Discount','Making Charge Off','Gift','Cashback','Loyalty Bonus']},fields:[['title','Offer title','text',true],['type','Offer type','select',true,['Discount','Making Charge Off','Gift','Cashback','Loyalty Bonus']],['value','Value','number'],['start_date','Start date','date',true],['end_date','End date','date',true],['customer_type','Customer type','select',false,['All','Normal','Premium','VIP','HNI']],['product_category','Product category'],['usage_limit','Usage limit','number'],['status','Status','select',false,['Active','Inactive']],['description','Description','textarea']]},
 'gift-cards':{title:'Gift Cards',singular:'Gift card',endpoint:'gift-cards',columns:[['code','Code'],['customer.name','Issued to'],['original_amount','Issued value'],['balance','Balance'],['status','Status']],filters:{status:['Active','Used','Expired','Cancelled']},fields:[['customer_id','Customer ID','number'],['original_amount','Card amount','number',true],['expiry_date','Expiry date','date',true]]},
 tasks:{title:'Tasks & Reminders',singular:'Task',endpoint:'tasks',columns:[['title','Task'],['assignee.name','Assigned to'],['due_at','Due'],['reward_points','Reward points'],['priority','Priority'],['status','Status']],filters:{status:['Pending','In Progress','Completed','Cancelled'],priority:['Low','Medium','High','Urgent']},fields:[['title','Task title','text',true],['description','Description','textarea'],['assigned_to','Staff ID','number'],['due_at','Due date & time','datetime-local',true],['reward_points','Completion reward points','number'],['priority','Priority','select',false,['Low','Medium','High','Urgent']],['status','Status','select',false,['Pending','In Progress','Completed','Cancelled']],['notes','Notes','textarea']]},
}
export const get=(obj,path)=>path.split('.').reduce((v,k)=>v?.[k],obj)
export const money=v=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(Number(v||0))
